// Full seed pack for structural-steel / hybrid-timber contractors (100 cost codes)
export const STEEL_FIELD_PACK = [
  // Logistics (1010-1100)
  { category: 'Logistics', code: '1010', description: 'Mobilize crew and equipment to site', active: false, isUsed: false },
  { category: 'Logistics', code: '1020', description: 'Off-load structural steel from trucks', active: false, isUsed: false },
  { category: 'Logistics', code: '1030', description: 'Shake-out and pre-sort members', active: false, isUsed: false },
  { category: 'Logistics', code: '1040', description: 'Rigging gear inspection & certification', active: false, isUsed: false },
  { category: 'Logistics', code: '1050', description: 'Site lay-down area setup', active: false, isUsed: false },
  { category: 'Logistics', code: '1060', description: 'Daily safety & toolbox meetings', active: false, isUsed: false },
  { category: 'Logistics', code: '1070', description: 'Traffic control & flagging', active: false, isUsed: false },
  { category: 'Logistics', code: '1080', description: 'Material handling - forklifts', active: false, isUsed: false },
  { category: 'Logistics', code: '1090', description: 'Temporary lighting & power', active: false, isUsed: false },
  { category: 'Logistics', code: '1100', description: 'Demobilize crew and equipment', active: false, isUsed: false },

  // Pre-Assembly (2010-2100)
  { category: 'Pre-Assembly', code: '2010', description: 'Assemble splice plates / field splices', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2020', description: 'Install temporary stiffeners', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2030', description: 'Bolt-hole reaming & touch-up', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2040', description: 'Trial-fit truss segments', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2050', description: 'Install shear studs to beams (shop)', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2060', description: 'Apply survey control lines', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2070', description: 'Pre-install bridging connectors', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2080', description: 'Set bearing pads on columns', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2090', description: 'Pre-assemble guardrail sections', active: false, isUsed: false },
  { category: 'Pre-Assembly', code: '2100', description: 'Stage members for crane picks', active: false, isUsed: false },

  // Rigging (3010-3100)
  { category: 'Rigging', code: '3010', description: 'Crane mobilisation & setup', active: false, isUsed: false },
  { category: 'Rigging', code: '3020', description: 'Engineer lift plans & permits', active: false, isUsed: false },
  { category: 'Rigging', code: '3030', description: 'Signal person / dogman activities', active: false, isUsed: false },
  { category: 'Rigging', code: '3040', description: 'Dual-crane picks coordination', active: false, isUsed: false },
  { category: 'Rigging', code: '3050', description: 'Night-shift rigging operations', active: false, isUsed: false },
  { category: 'Rigging', code: '3060', description: 'Crane relocation on site', active: false, isUsed: false },
  { category: 'Rigging', code: '3070', description: 'Rigging gear maintenance', active: false, isUsed: false },
  { category: 'Rigging', code: '3080', description: 'Crane demobilisation', active: false, isUsed: false },
  { category: 'Rigging', code: '3090', description: 'Hoist beam into position', active: false, isUsed: false },
  { category: 'Rigging', code: '3100', description: 'Hoist column into position', active: false, isUsed: false },

  // Erection (4010-4200)
  { category: 'Erection', code: '4010', description: 'Set base plates & grout verification', active: false, isUsed: false },
  { category: 'Erection', code: '4020', description: 'Plumb & align first tier columns', active: false, isUsed: false },
  { category: 'Erection', code: '4030', description: 'Erect upper tier columns', active: false, isUsed: false },
  { category: 'Erection', code: '4040', description: 'Erect primary beams/girders', active: false, isUsed: false },
  { category: 'Erection', code: '4050', description: 'Erect secondary beams/joists', active: false, isUsed: false },
  { category: 'Erection', code: '4060', description: 'Erect cantilever beams', active: false, isUsed: false },
  { category: 'Erection', code: '4070', description: 'Install bracing members', active: false, isUsed: false },
  { category: 'Erection', code: '4080', description: 'Install horizontal trusses', active: false, isUsed: false },
  { category: 'Erection', code: '4090', description: 'Install vertical trusses', active: false, isUsed: false },
  { category: 'Erection', code: '4100', description: 'Erect pipe columns / HSS', active: false, isUsed: false },
  { category: 'Erection', code: '4110', description: 'Install miscellaneous embeds', active: false, isUsed: false },
  { category: 'Erection', code: '4120', description: 'Install edge angles / kickers', active: false, isUsed: false },
  { category: 'Erection', code: '4130', description: 'Install canopy steel', active: false, isUsed: false },
  { category: 'Erection', code: '4140', description: 'Install stair stringers', active: false, isUsed: false },
  { category: 'Erection', code: '4150', description: 'Install landing frames', active: false, isUsed: false },
  { category: 'Erection', code: '4160', description: 'Install ladder cages', active: false, isUsed: false },
  { category: 'Erection', code: '4170', description: 'Install mechanical platform steel', active: false, isUsed: false },
  { category: 'Erection', code: '4180', description: 'Install roof screen supports', active: false, isUsed: false },
  { category: 'Erection', code: '4190', description: 'Install parapet girts', active: false, isUsed: false },
  { category: 'Erection', code: '4200', description: 'Install temporary erection aids', active: false, isUsed: false },

  // Bolting (5010-5100)
  { category: 'Bolting', code: '5010', description: 'Initial bolt-up / snug-tight', active: false, isUsed: false },
  { category: 'Bolting', code: '5020', description: 'Final torque - primary connections', active: false, isUsed: false },
  { category: 'Bolting', code: '5030', description: 'Final torque - secondary connections', active: false, isUsed: false },
  { category: 'Bolting', code: '5040', description: 'Tension control bolt inspection', active: false, isUsed: false },
  { category: 'Bolting', code: '5050', description: 'Replace damaged bolts', active: false, isUsed: false },
  { category: 'Bolting', code: '5060', description: 'Lubricate high-strength bolts', active: false, isUsed: false },
  { category: 'Bolting', code: '5070', description: 'Document bolt torque readings', active: false, isUsed: false },
  { category: 'Bolting', code: '5080', description: 'Ultrasonic bolt testing prep', active: false, isUsed: false },
  { category: 'Bolting', code: '5090', description: 'Install slip-critical joints', active: false, isUsed: false },
  { category: 'Bolting', code: '5100', description: 'Site cleanup of bolt debris', active: false, isUsed: false },

  // Welding (6010-6150)
  { category: 'Welding', code: '6010', description: 'Field weld column splices', active: false, isUsed: false },
  { category: 'Welding', code: '6020', description: 'Field weld beam splices', active: false, isUsed: false },
  { category: 'Welding', code: '6030', description: 'Weld diaphragm plates', active: false, isUsed: false },
  { category: 'Welding', code: '6040', description: 'Weld moment connections', active: false, isUsed: false },
  { category: 'Welding', code: '6050', description: 'Weld continuity plates', active: false, isUsed: false },
  { category: 'Welding', code: '6060', description: 'Weld stair stringers to headers', active: false, isUsed: false },
  { category: 'Welding', code: '6070', description: 'Weld handrail posts', active: false, isUsed: false },
  { category: 'Welding', code: '6080', description: 'Weld embed plates to steel', active: false, isUsed: false },
  { category: 'Welding', code: '6090', description: 'Pre-heat & inter-pass monitoring', active: false, isUsed: false },
  { category: 'Welding', code: '6100', description: 'Post-weld cleanup / slag removal', active: false, isUsed: false },
  { category: 'Welding', code: '6110', description: 'Mag-particle testing support', active: false, isUsed: false },
  { category: 'Welding', code: '6120', description: 'Ultrasonic testing support', active: false, isUsed: false },
  { category: 'Welding', code: '6130', description: 'Weld repair per RFI', active: false, isUsed: false },
  { category: 'Welding', code: '6140', description: 'Back-gouging / grinding', active: false, isUsed: false },
  { category: 'Welding', code: '6150', description: 'Weld deck angle supports', active: false, isUsed: false },

  // Decking (7010-7100)
  { category: 'Decking', code: '7010', description: 'Install metal roof deck', active: false, isUsed: false },
  { category: 'Decking', code: '7020', description: 'Install composite floor deck', active: false, isUsed: false },
  { category: 'Decking', code: '7030', description: 'Shear stud welding', active: false, isUsed: false },
  { category: 'Decking', code: '7040', description: 'Install closure/side plates', active: false, isUsed: false },
  { category: 'Decking', code: '7050', description: 'Install pour stop angles', active: false, isUsed: false },
  { category: 'Decking', code: '7060', description: 'Install deck screws / pins', active: false, isUsed: false },
  { category: 'Decking', code: '7070', description: 'Install deck reinforcement mesh', active: false, isUsed: false },
  { category: 'Decking', code: '7080', description: 'Edge form installation', active: false, isUsed: false },
  { category: 'Decking', code: '7090', description: 'Deck opening framing', active: false, isUsed: false },
  { category: 'Decking', code: '7100', description: 'Deck QA walkdown', active: false, isUsed: false },

  // Grouting (8010-8050)
  { category: 'Grouting', code: '8010', description: 'Template setup for grout', active: false, isUsed: false },
  { category: 'Grouting', code: '8020', description: 'Mix & place non-shrink grout', active: false, isUsed: false },
  { category: 'Grouting', code: '8030', description: 'Trim grout pads', active: false, isUsed: false },
  { category: 'Grouting', code: '8040', description: 'Final column alignment survey', active: false, isUsed: false },
  { category: 'Grouting', code: '8050', description: 'Torque anchor rods', active: false, isUsed: false },

  // QA/QC (9010-9100)
  { category: 'QA/QC', code: '9010', description: 'Fall protection & access setup', active: false, isUsed: false },
  { category: 'QA/QC', code: '9020', description: 'Daily safety inspection & permits', active: false, isUsed: false },
  { category: 'QA/QC', code: '9030', description: 'Torque verification inspections', active: false, isUsed: false },
  { category: 'QA/QC', code: '9040', description: 'Weld visual inspection (VT)', active: false, isUsed: false },
  { category: 'QA/QC', code: '9050', description: 'Coordinate NDT subcontractor', active: false, isUsed: false },
  { category: 'QA/QC', code: '9060', description: 'Record as-built survey data', active: false, isUsed: false },
  { category: 'QA/QC', code: '9070', description: 'Punch-list walkdown - steel frame', active: false, isUsed: false },
  { category: 'QA/QC', code: '9080', description: 'Close-out documentation prep', active: false, isUsed: false },
  { category: 'QA/QC', code: '9090', description: 'Final client turnover walk', active: false, isUsed: false },
  { category: 'QA/QC', code: '9100', description: 'Site housekeeping - final', active: false, isUsed: false },
];
