import { LegalDocType } from './legal.types';

export const DEFAULT_LEGAL_VERSION = 'beta-2025-12-13';

export const defaultLegalDocs = () => {
  const effectiveAt = new Date();

  const privacyPolicy = [
    'MYTE Construction OS (Beta) - Privacy Policy',
    '',
    'No legalese. No “we might sell your soul” clauses. Just the basics of how we handle data while we build this thing together.',
    '',
    '1) What this is',
    '- You are joining a beta playground.',
    '- You are helping shape the product by using it and giving feedback.',
    '- We build openly so you can inspect, learn, and self-host later if you want.',
    '',
    '2) What we collect',
    '- Account: name, email, password hash (never your raw password).',
    '- Organization/workspace: org name/domain, invites, roles (RBAC).',
    '- App data you create: projects, contacts, notes, etc. (as features roll out).',
    '- Security + audit: event logs (who did what, when), IP/user-agent for acceptance and session protection.',
    '- Cookies: a session cookie so you can stay signed in.',
    '- Emails: we send verification, invites, password resets, and product updates if you opt in.',
    '',
    '3) Why we collect it',
    '- To run the product (auth, sessions, roles, org scoping).',
    '- To keep the system safe (rate limits, abuse prevention, audit trails).',
    '- To improve the product (fix bugs, understand what’s working, prioritize the roadmap).',
    '',
    '4) What we do NOT do',
    '- We do not sell your personal data.',
    '- We do not read your password (we store a hash).',
    '',
    '5) Who can see what',
    '- Within your organization: admins/owners can manage users and invites for your org.',
    '- Platform admins: can see platform-level onboarding signals (waitlist, inquiries, org list) to run the beta.',
    '',
    '6) Where your data lives',
    '- Data is stored in our databases and logs.',
    '- Some orgs may use dedicated storage in the future; connection URIs are never exposed in the UI.',
    '',
    '7) Retention + deletion',
    '- We keep data as long as you use the beta, unless you request deletion.',
    '- If a legal hold is required (rare, but possible), deletion may be paused.',
    '',
    '8) Your choices',
    '- You can ask for access/export or deletion of your account data by contacting us.',
    '- You can opt out of marketing emails; critical account emails still go out (invites, security, resets).',
    '',
    '9) Changes',
    '- If we update this policy, we version it. You may be asked to accept the latest version to continue.',
    '',
    'Contact',
    '- Email us: mytecodysupport@mytegroup.com',
  ].join('\n');

  const terms = [
    'MYTE Construction OS (Beta) - Terms & Conditions',
    '',
    'Welcome to the beta. This is the “we’re building an ecosystem with you” version of terms. Short, clear, and honest.',
    '',
    '1) Beta means “not finished”',
    '- Things may break. Features may change. Data models may evolve.',
    '- We will do our best to protect your data, but do not treat this as your sole system of record yet.',
    '',
    '2) Your account + your org',
    '- Your account is for you. Do not share passwords.',
    '- Organizations have owners/admins who can invite teammates and manage roles.',
    '- If your company domain is already claimed, you’ll need an invite from that org to join.',
    '',
    '3) Use it like a pro',
    '- Don’t attack the service, scrape it, spam it, or try to bypass access controls.',
    '- Don’t upload anything illegal or abusive.',
    '',
    '4) Your data stays yours',
    '- You own the content you put into MYTE.',
    '- You give us permission to host and process it so the app can function.',
    '',
    '5) Feedback is fuel',
    '- If you give feedback, you’re letting us use it to improve the product.',
    '- You’re helping build what will eventually be sold or offered at affordable rates.',
    '',
    '6) Open build / sovereignty',
    '- We build openly so you can inspect how things work.',
    '- Over time, parts of the ecosystem may be self-hostable. You can trust us to run it, or run it yourself.',
    '',
    '7) Pricing (future)',
    '- Beta access may be free or discounted.',
    '- When we introduce paid plans, we’ll communicate clearly before charging.',
    '',
    '8) Warranty + liability (plain language)',
    '- This beta is provided “as is”. No promises that it’s perfect.',
    '- We’re not liable for indirect losses (like lost profits) from beta issues.',
    '',
    '9) Enforcement',
    '- If you violate these terms or abuse the platform, we can suspend access.',
    '',
    'Contact',
    '- Email us: mytecodysupport@mytegroup.com',
  ].join('\n');

  return [
    { type: LegalDocType.PrivacyPolicy, version: DEFAULT_LEGAL_VERSION, content: privacyPolicy, effectiveAt },
    { type: LegalDocType.Terms, version: DEFAULT_LEGAL_VERSION, content: terms, effectiveAt },
  ];
};

