export enum Role {
  SuperAdmin = 'superadmin',
  OrgOwner = 'org_owner',
  Admin = 'admin',
  PM = 'pm',
  Estimator = 'estimator',
  Engineer = 'engineer',
  Detailer = 'detailer',
  Transporter = 'transporter',
  Foreman = 'foreman',
  Superintendent = 'superintendent',
  QAQC = 'qaqc',
  HS = 'hs',
  Purchasing = 'purchasing',
  Compliance = 'compliance',
  Finance = 'finance',
  User = 'user',
}
